# Site settings
title: Coding blog
email: HaveFunCoding@gmail.com
description: My simple blog about coding.
baseurl: "/coding-blog"
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Leon Fortgens" # Set default author name
      categories: "coding"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
